### ISSUE TITLE
Horizontal Server List no longer works (as of the creation of this issue)

### ISSUE THREAD

**Issue by Shigbeard** [GoldenLys/BetterDiscord-Elysia#3]
As it says on the can. Horizontal Server List isn't horizontal. Currently, it tries to do horizontal with grouped servers, but for the most part it fails entirely and the servers continue to stack vertically.

[Here's a video](https://img.fluttershub.com/ciwklf1m.webm)

**Comment by Shigbeard** [comment]
The issue seems to have resolved itself as for 2/04/2020. It appears to have been a discord related bug. As such, I'm closing this issue.

**Comment by GoldenLys** [comment]
I posted an update for it, but i needed to re-design the server list ^^
