### ISSUE TITLE
Servers list is empty

### ISSUE THREAD

**Issue by fishingboatproceeded** [GoldenLys/BetterDiscord-Elysia#4]
I'm on Xubuntu, using Snap Discord. On my Windows machine this theme works great but when I installed it on Linux the top bar appeared empty, but I could still access my servers using key bindings to navigate.

It also appears that the title bar is gone as well.

The only other theme I am using is RadialStatus by Gibbu (v 1.0.0)

![image](https://user-images.githubusercontent.com/42788817/80845080-35cb4e80-8bd6-11ea-9192-6b5fcb2fd481.png)

**Comment by fishingboatproceeded** [comment]
It also appears that if I install Horizontal Server List and use it without the theme enabled it works

**Comment by GoldenLys** [comment]
Sorry i can't support linux since i don't use it. The theme only supports windows
