### ISSUE TITLE
Syntax issue when using theme generator.

### ISSUE THREAD

**Issue by KanjiuAkuma** [GoldenLys/BetterDiscord-Elysia#7]
When using the theme editor/generator (https://goldenlys.github.io/ThemeGen) there is an issue with the '--logo' (line 35):
The " (quotes) are placed wrong and therefore the logo does not load in discord:
Line 35 is : --logo: "url(someUrl)";
should be:  --logo: url("someUrl");

Steps to reproduce: Open theme generator and generate theme with default settings.

**Comment by GoldenLys** [comment]
Already fixed yesterday, someone else told me on discord 😉
