### ISSUE TITLE
Text channels have voice channel icons

### ISSUE THREAD

**Issue by LordMZTE** [GoldenLys/BetterDiscord-Elysia#8]
![image](https://user-images.githubusercontent.com/28735087/90310144-117a5000-deef-11ea-93d9-9b4161514970.png)

in this image, you can see that all the text channels have voice channel icons and the dev tools show that this icon is coming from elysia's css file

**Comment by GoldenLys** [comment]
yes, i already fixed this, discord actually made some changes ;)
